/* Generated by Amaranth Yosys 0.10.0 (PyPI ver 0.10.0.dev47, git sha1 dca8fb54a) */

(* \amaranth.hierarchy  = "top" *)
(* top =  1  *)
(* generator = "Amaranth" *)
module top(rs2, f3, rd, clk, rst, rs1);
  reg \initial  = 0;
  (* src = "/home/ggangliu/first-riscv/src/alu.py:21" *)
  wire \$1 ;
  (* src = "/home/ggangliu/first-riscv/src/alu.py:25" *)
  wire [32:0] \$10 ;
  (* src = "/home/ggangliu/first-riscv/src/alu.py:25" *)
  wire [33:0] \$12 ;
  (* src = "/home/ggangliu/first-riscv/src/alu.py:25" *)
  wire [33:0] \$3 ;
  (* src = "/home/ggangliu/first-riscv/src/alu.py:25" *)
  wire [31:0] \$4 ;
  (* src = "/home/ggangliu/first-riscv/src/alu.py:25" *)
  wire [32:0] \$6 ;
  (* src = "/home/ggangliu/first-riscv/src/alu.py:25" *)
  wire [32:0] \$8 ;
  (* src = "/home/ggangliu/.local/lib/python3.8/site-packages/amaranth/hdl/ir.py:527" *)
  input clk;
  (* src = "/home/ggangliu/first-riscv/src/alu.py:11" *)
  input [3:0] f3;
  (* src = "/home/ggangliu/first-riscv/src/alu.py:14" *)
  output [31:0] rd;
  reg [31:0] rd;
  (* src = "/home/ggangliu/first-riscv/src/alu.py:12" *)
  input [31:0] rs1;
  (* src = "/home/ggangliu/first-riscv/src/alu.py:13" *)
  input [31:0] rs2;
  (* src = "/home/ggangliu/.local/lib/python3.8/site-packages/amaranth/hdl/ir.py:527" *)
  input rst;
  (* src = "/home/ggangliu/first-riscv/src/alu.py:20" *)
  reg ta = 1'h0;
  (* src = "/home/ggangliu/first-riscv/src/alu.py:20" *)
  reg \ta$next ;
  assign \$10  = f3[3] ? (* src = "/home/ggangliu/first-riscv/src/alu.py:25" *) \$6  : \$8 ;
  assign \$12  = $signed(rs1) + (* src = "/home/ggangliu/first-riscv/src/alu.py:25" *) $signed(\$10 );
  assign \$1  = ~ (* src = "/home/ggangliu/first-riscv/src/alu.py:21" *) ta;
  assign \$4  = ~ (* src = "/home/ggangliu/first-riscv/src/alu.py:25" *) rs2;
  assign \$6  = \$4  + (* src = "/home/ggangliu/first-riscv/src/alu.py:25" *) 1'h1;
  assign \$8  = + (* src = "/home/ggangliu/first-riscv/src/alu.py:25" *) $signed(rs2);
  always @(posedge clk)
    ta <= \ta$next ;
  always @* begin
    if (\initial ) begin end
    \ta$next  = \$1 ;
    (* src = "/home/ggangliu/.local/lib/python3.8/site-packages/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \ta$next  = 1'h0;
    endcase
  end
  always @* begin
    if (\initial ) begin end
    rd = 32'd0;
    (* src = "/home/ggangliu/first-riscv/src/alu.py:23" *)
    casez (f3[2:0])
      /* src = "/home/ggangliu/first-riscv/src/alu.py:24" */
      3'h0:
          rd = \$12 [31:0];
    endcase
  end
  assign \$3  = \$12 ;
endmodule
