/* Generated by Amaranth Yosys 0.10.0 (PyPI ver 0.10.0.dev47, git sha1 dca8fb54a) */

(* \amaranth.hierarchy  = "top.U$$0" *)
(* generator = "Amaranth" *)
module \U$$0 ();
  wire \$empty_module_filler ;
endmodule

(* \amaranth.hierarchy  = "top" *)
(* top =  1  *)
(* generator = "Amaranth" *)
module top(rst, clk);
  (* src = "elaborate_main.py:8" *)
  input clk;
  (* src = "elaborate_main.py:8" *)
  input rst;
  \U$$0  \U$$0  (
  );
endmodule

